name: publish-binaries

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: 01_Trimesh_Tiling
            asset_name: 01_Trimesh_Tiling-linux-amd64
          - os: windows-latest
            artifact_name: 01_Trimesh_Tiling.exe
            asset_name: 01_Trimesh_Tiling-windows-amd64
          - os: macos-latest
            artifact_name: 01_Trimesh_Tiling
            asset_name: 01_Trimesh_Tiling-macos-amd64

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - name: Build-Windows
      if: matrix.os == 'windows-latest'
      run: |
            sed -i '25d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
            sed -i '24d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
            sed -i '23d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
            sed -i '22d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
            cd examples
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" 
            cmake --build . --config Release --parallel 8
    - name: Build-Unix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
            cd examples
            mkdir build
            cd build
            cmake .. -DCMAKE-BUILD_TYPE=Release
            cmake --build . --parallel 8
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: examples/build/01_Trimesh_Tiling/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
