name: windows-build

on:
  push:
    paths:
    - examples/**
    - include/**
    - external/**
    - .github/workflows/windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: |
          cd examples
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" 
          cmake --build . --config Release --parallel 8
