name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: build
        shell: bash
        run: |
          cd examples
          mkdir -p build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_CXX_STANDARD=11 ..
          make -j8
      #- name: test
      #  shell: bash
        # run: |
          # echo "./test.sh"
